[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "webcitizen"
version = "0.1.0"
description = "SEO audits for websites"
readme = "README.md"


[project.urls]
homepage = "https://github.com/prasannakulkarni333/python-webcitizen-audit"